### ISSUE TITLE
hi I have a problem, I'm using a bukkitgpt but it gives me an error

### ISSUE THREAD

**Issue by Alexissc639** [CubeGPT/BukkitGPT#12]
error and because of the base url I'm sorry I'm a bit new to this but I don't know what to put in it,.
please help me

**Comment by lolo45654** [comment]
Hi there, it would be helpful to the maintainer if you could provide the error stacktrace. If you use OpenAI, you don't need to put anything in the `BASE_URL` config option. That is for more advanced usage.

**Comment by Alexissc639** [comment]
yes, but it gives me an error in _base_client.py from the open package to Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai\_base_client.py", line 952, in _request
     raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

**Comment by lolo45654** [comment]
Sorry, the `BASE_URL` should contain `https://api.openai.com/v1/`. My bad!

**Comment by Zhou-Shilin** [comment]
Use `https://api.openai.com/v1`.
