### ISSUE TITLE
我今天使用时发现的各类错误

### ISSUE THREAD

**Issue by FQO3** [CubeGPT/BukkitGPT#17]
1.运行console.py时的update环节时，报错证书验证失败（可能是因为我的加速器原因）
![image](https://github.com/CubeGPT/BukkitGPT/assets/111474347/4dd903a8-0c89-4040-bafb-4cb5552dd9b7)
可使用禁止验证证书修复，但是每次启动时会提示启用证书

2.开启BETTER_DESCRIPTION开始生成后报错：
![image](https://github.com/CubeGPT/BukkitGPT/assets/111474347/a6ba0774-fff2-4959-aaf4-40662dc3cb18)
我是搞C++的，python不太熟悉，但是看了看好像是变量类型的问题……？不知道在为啥
[May-04-14-07-33-2024.log](https://github.com/CubeGPT/BukkitGPT/files/15208176/May-04-14-07-33-2024.log)

3.重新生成时没写package_list参数导致报错：
![image](https://github.com/CubeGPT/BukkitGPT/assets/111474347/5a0ca3ad-22de-40fc-9321-51c19e98b828)

4.希望生成失败后将/projects下刚刚生成错误的项目自动打包并移动到如debug等文件夹中，防止下次生成时提示文件已存在：
![image](https://github.com/CubeGPT/BukkitGPT/assets/111474347/8bdd76ea-fa44-4861-91b9-2ff780df3800)

然后感觉你们真的很厉害，我今年初二，也是搞编程的，希望交个朋友哈

**Comment by Zhou-Shilin** [comment]
感谢反馈～
这些问题会在下一个版本修复。
