### ISSUE TITLE
No matter what I install it will never find YAML

### ISSUE THREAD

**Issue by Solar9174** [CubeGPT/BukkitGPT#19]
I have been trying to fix this for hours and its doesnt matter what i install or change it never find yaml, im going crazy over this

**Comment by Zhou-Shilin** [comment]
I finally found what the problem was. You need to cd into BukkitGPT's folder first and then run it, not run it by entering the full path in another folder.

And please use `console.py` for now instead of `ui.py`, bcuz i just found an bug in ui.py in the lastest version.
