### ISSUE TITLE
ImportError: cannot import name 'OpenAI' from 'openai'

### ISSUE THREAD

**Issue by zip8919** [CubeGPT/BukkitGPT#7]
Traceback (most recent call last):
  File "G:\BukkitGPT-2.0.0\ui.py", line 13, in <module>
    import core
  File "G:\BukkitGPT-2.0.0\core.py", line 1, in <module>
    from openai import OpenAI
ImportError: cannot import name 'OpenAI' from 'openai' (D:\ProgramData\Anaconda3\lib\site-packages\openai\__init__.py)

**Comment by Zhou-Shilin** [comment]
You need to install the package openai.
Run this command in bash.
```bash
pip install openai
```

**Comment by Zhou-Shilin** [comment]
Has the issue been resolved? If resolved, please close this issue.
